services:
  app:
    build: .
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      desafio_net:
        ipv4_address: 172.10.0.2
    environment:
      TZ: America/Sao_Paulo
    command: sh -c "npm install && gulp watch & apache2-foreground"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: desafio_revvo
      MYSQL_DATABASE: desafio_revvo
      MYSQL_USER: desafio
      MYSQL_PASSWORD: desafio_revvo
      TZ: America/Sao_Paulo
    ports:
      - "6033:3306"
    volumes:
      - ./app/db/starter.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      desafio_net:
        ipv4_address: 172.10.0.3

networks:
  desafio_net:
    ipam:
      config:
        - subnet: 172.10.0.0/24